#pragma once

#include "OTPGuideDataStruct.h"


enum OTPWriterErrorCode
{
	OTPWRITER_ERROR_OK = 0,
	OTPWRITER_ERROR_JPGHEAD,
	OTPWRITER_ERROR_JPGLOGO,
	OTPWRITER_ERROR_MAPCOL1234,
	OTPWRITER_ERROR_CALC_SECTION_COL,
	OTPWRITER_ERROR_CHANGE_HISTORY_DATE,
	OTPWRITER_ERROR_CHANGE_HISTORY_EMPTY,
	OTPWRITER_ERROR_EXCEL_ROW_EMPTY,
	OTPWRITER_ERROR_PDF_EXCEPTION,
	OTPWRITER_ERROR_CREATE_PDFDOC,
	OTPWRITER_ERROR_WRITE_PDFFILE,
	OTPWRITER_ERROR_ENGLISH_CONTENT_OUTOFLINE,
	OTPWRITER_ERROR_ADDR_OUT_OF_MAP_RANGE
};

int OTPGuideInfo2Pdf(OTPGuideInfo& otpGuideInfo, string strSaveFileFolder);